### ISSUE TITLE
Wiki: создать общедоступную базу знаний.

### ISSUE THREAD

**Issue by fungoter** [windir77/Sowmud#10]

**Comment by fungoter** [comment]
Парсинг команды "зоны" в mediawiki-формат:
```
^(\s?)(\d+)  ([А-Яа-я"]+)((\s?[-А-Яа-я"]+)*)(\s{2,})(\d+)-(\d+)  ([А-Яа-я"]+)(([,]\s[А-Яа-я"]*)*)(\s{2,})(.+)

|-\n|$2\n|[[$3$4]]\n|$7\n|$8\n|$9$10\n|$13
```

**Comment by Rorifer** [comment]
У меня немного другой код получился чета..

{| border="1"
|-									
||	Номер	||	Название	||	Уровни	||	Авторы	||	Местоположение
|-
||	10	||	Арена	||	1-30	||	Бенедикт	||	Порталы в гостиницах
|-
||	12	||	Город Стэдвик	||	10-32	||	Аррид	||	Восточнее Фелонада
|-
||	16	||	Замок Стэдвика	||	33-38	||	Хизмедар	||	Находится в Стэдвике
|-
||	17	||	Долина Дракона	||	38-42	||	Хизмедар	||	Вход из города Стэдвик
|-
||	19	||	Мад-школа	||	1- 3	||	Алоня	||	Севернее гостиницы в Элендоре
|-
||	22	||	Зоопарк	||	23-28	||	Талира, Разиэль	||	Находится в Фелонаде
|-
||	49	||	Турнирный городок	||	1-40	||	Дэрверон	||	Межреальность
|-
||	50	||	Поляна ночных эльфов	||	35-40	||	Дэрверон	||	Рядом с Турнирным городком
|-
||	51	||	Обелиск заклинателей	||	35-40	||	Дэрверон	||	На дороге Артуанель-Шиар
|-
||	52	||	Обелиск благословения	||	35-40	||	Дэрверон	||	На дороге Фелонад-Стэдвик
|-
||	75	||	Поляна в густом лесу	||	12-22	||	Ярость	||	Северо-восточнее Элендора
|-
||	76	||	Замок повелителя стихий	||	33-36	||	Ярость	||	Севернее Видрира
|-
||	96	||	Военный гарнизон	||	30-34	||	Эпимитриус	||	К западу от Шиара
|-
||	97	||	Далекая крепость	||	25-32	||	Хизмедар	||	На востоке от Шиара
|-
||	98	||	Здание стражи Элендора	||	5-10	||	Хизмедар	||	Находится в Элендоре
|-
||	99	||	Город Шиар	||	15-30	||	Эпимитриус	||	На северо-востоке от Артуанеля
|-
||	100	||	Город Элендор	||	10-30	||	Алоня, Бенедикт	||	В нем вы родились
|-
||	101	||	Развалины Элендора	||	15-30	||	Бенедикт	||	Находится в Элендоре
|-
||	102	||	Канализация	||	5-10	||	Рианс	||	Находится в Элендоре
|-
||	103	||	Притон	||	7-18	||	Рианс, Виана	||	Находится в Элендоре
|-
||	105	||	Темный лес	||	7-12	||	Алоня	||	Северо-восточнее Элендора
|-
||	106	||	Парк	||	3- 8	||	Алоня	||	Находится в Элендоре
|-
||	108	||	Лагерь гоблинов	||	15-22	||	Бенедикт	||	В северной части Яра
|-
||	109	||	Яр	||	10-16	||	Алоня	||	На восточной дороге
|-
||	110	||	Башня магов	||	10-22	||	Дэкар	||	Находится в Элендоре
|-
||	111	||	Болото	||	7-12	||	Оркаэн	||	Юго-восточнее Элендора
|-
||	112	||	Эльфийская застава	||	15-25	||	Бенедикт	||	В северной части Темного леса
|-
||	113	||	Кладбище	||	10-30	||	Алоня	||	Юго-восточнее Элендора
|-
||	114	||	Склад в Геоланте	||	10-18	||	Оркаэн	||	Находится в Геоланте
|-
||	115	||	Город Геолант	||	15-30	||	Алоня	||	На востоке от Элендора
|-
||	116	||	Магический лес	||	20-30	||	Алоня	||	В окрестностях Геоланта
|-
||	117	||	Деревня рыбаков	||	15-20	||	Лорана	||	Юго-восточнее болота
|-
||	119	||	Храм пламенного меча	||	20-25	||	Гека	||	На востоке от Геоланта
|-
||	120	||	Каньон поющей воды	||	20-25	||	Бенедикт	||	Северо-восточнее Геоланта
|-
||	121	||	Южный лес	||	18-30	||	Гека	||	Юго-восточнее Геоланта
|-
||	123	||	Тюрьма в Геоланте	||	22-28	||	Лорана	||	Находится в Геоланте
|-
||	124	||	Домик у дороги	||	18-23	||	Стрина	||	Рядом с фермой
|-
||	125	||	Город Артуанель	||	15-30	||	Бенедикт	||	За эльфийской заставой
|-
||	126	||	Дремучий лес	||	20-27	||	Бенедикт	||	В окрестностях Артуанеля
|-
||	128	||	Порт Элендора	||	15-20	||	Алоня	||	Вход находится в Элендоре
|-
||	129	||	Подземелье гномов	||	22-28	||	Игнат	||	Юго-восточнее Геоланта
|-
||	130	||	Орочья башня	||	20-25	||	Бритир	||	На северной дороге от Геоланта
|-
||	131	||	Чайный домик	||	14-18	||	Стрина	||	Находится в Геоланте
|-
||	132	||	Лагерь археологов	||	15-25	||	Данкис	||	Западнее Геоланта
|-
||	133	||	Ущелье гарпий	||	26-29	||	Левар	||	Вход из Горной цепи
|-
||	134	||	Преисподняя	||	26-35	||	Дэкар	||	Под кладбищем Элендора
|-
||	135	||	Дом с привидениями	||	10-18	||	Алоня	||	Между Геолантом и Огисом
|-
||	136	||	Окрестные поля	||	8-15	||	Кальви	||	На юге от Элендора
|-
||	137	||	Окружная дорога	||	20-30	||	Кальви	||	На юге от Элендора
|-
||	138	||	Муравейник	||	26-31	||	Кэш	||	Юго-восточнее Фелонада
|-
||	139	||	Кузница	||	12-18	||	Ниеми	||	На юг от Геоланта
|-
||	140	||	Заливные луга	||	15-22	||	Кальви	||	На юге Окрестных полей Элендора
|-
||	141	||	Город Эрдер	||	27-30	||	Фацур	||	Пройдя через тьму
|-
||	142	||	Во тьме	||	27-30	||	Фацур	||	Где-то в шахтах Фелонада
|-
||	143	||	Восточная окраина Эрдера	||	27-30	||	Фацур	||	К востоку от Эрдера
|-
||	144	||	Крепость Тима	||	25-30	||	Кэш	||	На южной дороге от Геоланта
|-
||	145	||	Осажденный замок	||	30-35	||	Кэш	||	Восток от Фелонада
|-
||	146	||	Аллея	||	4- 8	||	Талина	||	Находится в Элендоре
|-
||	147	||	Крепость	||	30-35	||	Кэш	||	Западнее Фелонада
|-
||	148	||	Ветренное плоскогорье	||	33-36	||	Кэш	||	Севернее Видрира
|-
||	149	||	Трактир "У Лиса"	||	20-25	||	Димид	||	На южной дороге от Геоланта
|-
||	150	||	Ферма	||	10-15	||	Алташ	||	Южнее Геоланта
|-
||	151	||	Крепость ужаса	||	25-30	||	Мэлайс	||	Северо-восточнее Геоланта
|-
||	152	||	Подземелье ужаса	||	30-35	||	Шиллу	||	Под Крепостью Ужаса
|-
||	153	||	Лагерь кочевников	||	18-23	||	Анабиела	||	Тропинка на юг от болота
|-
||	154	||	Селение людоедов	||	28-32	||	Кровт	||	На юг от Геоланта
|-
||	155	||	Старая церковь	||	20-25	||	Алоня	||	Находится в Фелонаде
|-
||	156	||	Больница	||	20-25	||	Лиолан	||	Находится в Элендоре
|-
||	157	||	Селение человекоящеров	||	18-22	||	Дэрверон	||	В яру южнее лагеря гоблинов
|-
||	158	||	Старая библиотека	||	15-18	||	Дэрверон	||	В развалинах Элендора
|-
||	159	||	Башня вихря	||	24-28	||	Дэрверон	||	Восточнее хутора Аргниста
|-
||	160	||	Тоннель бесов	||	22-25	||	Дэрверон	||	В северной части Темного леса
|-
||	161	||	Холм фаэри	||	22-25	||	Хизмедар	||	На восток от Южного леса
|-
||	162	||	Глубокая расщелина	||	33-38	||	Дэрверон	||	Вход в тоннеле бесов
|-
||	163	||	Западные равнины	||	18-25	||	Хизмедар	||	Западнее поселка хоббитов
|-
||	166	||	Башенное кольцо	||	25-30	||	Эпимитриус	||	Где-то в развалинах Элендора
|-
||	169	||	Парк аттракционов	||	10-15	||	Бенедикт	||	Находится в Элендоре
|-
||	170	||	Замок Элендора	||	30-35	||	Дэрверон	||	Является частью Дворца Элендора
|-
||	177	||	Драконий остров	||	30-35	||	Легвил	||	Где-то в океане
|-
||	180	||	Город Огис	||	20-35	||	Талина	||	В северных горах
|-
||	181	||	Конюшни	||	15-20	||	Талина	||	Южная улица в Огисе
|-
||	182	||	Лечебница для животных	||	8-15	||	Талина	||	Зеленая улица в Огисе
|-
||	183	||	Древнее капище	||	20-25	||	Дэрверон	||	На западе от Огиса
|-
||	186	||	Подземелье драконов	||	33-38	||	Иллирил	||	Рядом с дорогой Шиар - Огис
|-
||	187	||	Северная деревня	||	19-25	||	Хизмедар	||	На западе от Огиса
|-
||	188	||	Пятипалая гора	||	40-45	||	Хизмедар	||	На востоке от Шиара
|-
||	198	||	Город Фелонад	||	20-30	||	Алоня	||	На востоке от Геоланта
|-
||	199	||	Паучьи пещеры	||	20-25	||	Алоня	||	Дорога на юг от храма
|-
||	201	||	Заколдованная долина	||	25-30	||	Талина	||	На северо-восток от Фелонада
|-
||	202	||	Лаборатория Фелонада	||	30-33	||	Буйлат	||	Находится в Фелонаде
|-
||	203	||	Деревня варваров	||	25-30	||	Ярость	||	На восток от Фелонада
|-
||	209	||	Туманное болото	||	30-35	||	Кэш	||	На границе Южного леса
|-
||	213	||	Закрытые шахты Фелонада	||	28-33	||	Хизмедар	||	Севернее Фелонада
|-
||	226	||	Катакомбы Геоланта	||	12-30	||	Аррид	||	Под Геолантом
|-
||	253	||	Гильдия головорезов	||	18-23	||	Хизмедар	||	В Огисе
|-
||	301	||	Хутор Аргниста	||	20-30	||	Ямерт	||	Хьервард
|-
||	302	||	Логовище орды	||	25-30	||	Ямерт	||	Северо-западнее хутора Аргниста
|-
||	304	||	Ангельские горы	||	35-40	||	Хизмедар	||	На севере Хъерварда
|-
||	305	||	Искрящийся замок	||	38-43	||	Хизмедар	||	На севере от Галена
|-
||	311	||	Морское побережье	||	25-30	||	Игнат	||	На восток от трактира "У Лиса"
|-
||	331	||	Старый дом в Огисе	||	33-38	||	Хизмедар	||	В Огисе
|-
||	333	||	Пирамида	||	33-38	||	Талира	||	В Хьерварде у побережья
|-
||	355	||	Лагерь полуорков	||	20-25	||	Игнат	||	Где-то на морском побережье
|-
||	356	||	Кладбище полуорков	||	24-30	||	Игнат	||	Рядом с лагерем полуорков
|-
||	380	||	Рыцарский рубеж	||	22-27	||	Ямерт	||	Юго-западнее хутора Аргниста
|-
||	402	||	Цитадель ордена	||	32-37	||	Рио	||	На юг от Видрира
|-
||	423	||	Больница Геоланта	||	25-30	||	Накхор	||	В Геоланте
|-
||	430	||	Дом ордена инквизиторов	||	32-37	||	Талира	||	Рядом с Ветренным плоскогорьем
|-
||	444	||	Горная цепь	||	20-28	||	Фальникар	||	На Северо-востоке от Геоланта
|-
||	450	||	Город Гален	||	25-35	||	Хизмедар	||	К востоку от Видрира
|-
||	451	||	Галерея Славы	||	38-45	||	Игроки	||	Вход из Зала героев Галена
|-
||	452	||	Горный перевал	||	25-30	||	Уина	||	Между Видриром и Галеном
|-
||	454	||	Канализация Галена	||	30-35	||	Хизмедар	||	Под городом Галеном
|-
||	455	||	Дома в Галене	||	24-35	||	Хизмедар	||	В городе Галене
|-
||	456	||	Живые скалы	||	34-40	||	Дален	||	На восток от Галена
|-
||	457	||	Храм Хедина	||	38-40	||	Хизмедар	||	На восток от Галена
|-
||	458	||	Адмиралтейство	||	28-32	||	Ямерт	||	Имперская площадь Галена
|-
||	459	||	Библиотека Галена	||	32-36	||	Хизмедар	||	Юго-восточная часть Галена
|-
||	460	||	Галенский морской форт	||	38-43	||	Хизмедар	||	В море недалеко от Галена
|-
||	461	||	Священная роща	||	33-38	||	Хизмедар	||	Рядом с главной площадью Галена
|-
||	462	||	Школа Меча	||	24-30	||	Дален	||	К востоку от Галена
|-
||	463	||	Курганы Богов	||	38-44	||	Хизмедар	||	Недалеко от болот Галена
|-
||	464	||	Арена испытаний	||	39-45	||	Дален	||	Вход из Школы Меча
|-
||	490	||	Поселок хоббитов	||	10-17	||	Кчарк	||	Севернее Элендорского порта
|-
||	496	||	Механическая башня	||	35-40	||	Хизмедар	||	Между Видриром и Рыцарским рубежом
|-
||	497	||	Старое кладбище	||	30-38	||	Дален	||	К востоку от хутора Аргниста
|-
||	499	||	Город Видрир	||	24-29	||	Игнат	||	На юге Хьерварда
|-
||	511	||	Затерянный остров	||	15-25	||	Рианс	||	Вход находится в Элендоре
|-
||	512	||	Дорога на Кронк-а-мор	||	25-30	||	Альтанер	||	На севере от Эльфийского города
|-
||	513	||	Кронк-а-мор	||	27-32	||	Альтанер	||	По дороге на Кронк-а-мор
|-
||	556	||	Лабиринт	||	35-39	||	Разиэль	||	Дорога на юг от храма
|-
||	718	||	Змеиное гнездо	||	27-30	||	Эйтшар	||	В яру
|-
||	781	||	Таверна "Борода тролля"	||	15-18	||	Хизмедар	||	На севере от Геоланта
|-
||	800	||	Безумие	||	27-33	||	Микуур	||	По дороге на Видрир
|-
 |}

**Comment by fungoter** [comment]
Можно и 2 палочки, но я записывал не в строку, а каждую ячейку с новой строки, потому и \n вставлено: \n - для перехода на новую строку.
Таблица сортируемая, поэтому MIN/MAX левлы  разделены на столбцы.

**Comment by Rorifer** [comment]
Здорого) не знал что лаба круче ПД)

**Comment by Rorifer** [comment]
Фаготен создал! =)

https://sow.fandom.com/ru/wiki/%D0%A1%D1%84%D0%B5%D1%80%D0%B0_%D0%9C%D0%B8%D1%80%D0%BE%D0%B2_%D0%92%D0%B8%D0%BA%D0%B8
