### ISSUE TITLE
Дескриминация по тригерному признаку.

### ISSUE THREAD

**Issue by Rorifer** [windir77/Sowmud#14]
Видоизменить следущие зоны:
1. Шахты (корректировка проверки размера в лазе)
2. Замок Стэдвика - открытие трона по благо (сейчас святой обряд)
...
Добавляем в коменты еще места, требующие спецскилов.

**Comment by windir77** [comment]
Для некоторых триггеров в зонах добавлены варианты заклинаний, активирующие
х: в зоне 'Замок Стэдвика' к святому обряду добавлено благословение, в зоне
Закрытая шахта Фелонада' к армагеддону добавлены все заклинания сферы огня
