### ISSUE TITLE
Ратрий: Перевязка

### ISSUE THREAD

**Issue by Rorifer** [windir77/Sowmud#24]
Проработать изменение перевязки
Цели:
1. Сделать полезным на низких уровнях
2. Сделать актуальным восстановление ХП на высоких уровнях.
3. Снизить кулдаун.
Рамки: 8 градаций
to be continium...

**Comment by Rorifer** [comment]
1. Кулдаун снизить до 5 минут.
2. Восстановление ХП от перевязки привязать к :  
max( 22d28*раскачка, раскачка*(процент от здоровья персонажа))
3.  Заменить 3 градацию на наложение аффекта регенерации равно 1/2 от раскачки перевязки.

**Comment by windir77** [comment]
Улучшено действие умения 'перевязка': уменьшен кд, увеличены вылечиваемые
ты и набор снимаемых аффектов, появилась возможность применения в бою.
дробнее см. раздел справки ПЕРЕВЯЗКА.
