### ISSUE TITLE
Ратрий: Модификация к регенерации здоровья.

### ISSUE THREAD

**Issue by Rorifer** [windir77/Sowmud#25]
1. убрать зависимость от уровня в регенерации здоровья.
2. изменить коэфицент регенерации во сне до х8
3. Изменить коэфицент регенерации при отдыхе до х4.

![image](https://cloud.githubusercontent.com/assets/15780798/17732264/990faf5a-6479-11e6-8c3e-bf23c1030d83.png)

**Comment by windir77** [comment]
** [11.09.2016 19:00] 

    Теперь в положении 'Отдыхает' скорость регенерации хитов составляет не 150%
  от нормы, а 400%, в положении 'Спит' - не 200%, а 800%.
