### ISSUE TITLE
переделка ветров

### ISSUE THREAD

**Issue by windir77** [windir77/Sowmud#3]
ИГРИВЫЕ ВЕТЕРКИ: всего будет штук 10, ходят медленно, при рипе имеют 50% шанс, что ВСЕХ чаров с ПЛАТО вынесет в первую клетку плато. Ветерки не репопят.

**Comment by windir77** [comment]
Изменение ПЛАТО: ветерков убираем собственно и триг птицы тож, про нее потом подумаю. на самом плато: ставим 3 ветрянные стены (типа ураган), чтобы преодолеть стену (она не пускат вперед) нужно убить всех мобов, которые окажутся с _нашей стороны_ стены, как только их караем - стена уходит, и так 3 стены на всем плато, а если убить ураган - пропадают все стены и можно идти в крепость считай спокойно
мобы ходят туда-сюда в обычном порядке, т.е перед скидыванием стены будет цикл по клеткам перед стеной, если пусто - выключаемся

**Comment by windir77** [comment]
Изменение КРЕПОСТИ: у нас есть же 2 коридора до хозы и хоза, предлагаю сделать до них путь отдельный специфический: у нас есть 1 клетка куда приходят девка парень, а со следующей клетки (первая южная) вот как будет - будет разделение на подкоридоры, заходя на клетку всех игроков определяет направо или налево (не разбрасывает, а перенаправляет всех в одно место) дальше там несколько клеток с группами/мобами, и оттуда выход на вторую клетку основного коридора, там снова разделение, так же с третьей клеткой, и в конце выход под рычаг. клетки куда кидает составы одинаковы для коридоров хоза или хозы, но конечные клетки с выходом уже другие - под тот рычаг который надо (если шли со стороны хозы, или если шли со стороны хозяйки.

**Comment by windir77** [comment]
Изменение птицы: ???

**Comment by Rorifer** [comment]
А может просто сделать чтоб ураган спаунился сразу, а ветерки не репопили?

**Comment by windir77** [comment]
ИГРИВЫЕ ВЕТЕРКИ: всего будет штук 10, ходят медленно, при рипе имеют 50% шанс, что ВСЕХ чаров с ПЛАТО вынесет в первую клетку плато. Ветерки не репопят.

**Comment by Dexx121** [comment]
Поддерживаю идею с тем, чтобы ветерки не репопили и чтобы зона сразу репопилась вся, а не как щас, частями. 

(Аморка)

**Comment by Rorifer** [comment]
Если ветерки репопить не будут а всех персов с  плата будет выносить в 1 клетку - напишу сценарий для бота сразу после введения...

**Comment by Dexx121** [comment]
Дык вы же и делаете все для своих ботов. У нас из ботящих только пият и то уже не каждую ночь.

**Comment by windir77** [comment]
я для ботов ничо не делают, тут цель оставить в ветрах невозможность заботить зону после изменений тоже

**Comment by Rorifer** [comment]
Ну так написали уже... сделать чтоб ветерки не репопили (потому что они реально парят) и сделать чтоб ураган репопил сразу.. Заботить зону конеш моно будет, но для этого придется каждый сбив призываться, бежать снова.. и т.п. и т.д.. это сведет ботинг зоны к "не выгодному" обычному же игроку... ветерки убиваются быстро, дт там нет.. лишняя минута... по мне так не особ сильно его это напряжет

**Comment by windir77** [comment]
Отправлено Имплементатору!

**Comment by fungoter** [comment]
** [20.08.2016 22:00]
    Внесены изменения в зону "Ветренное плоскогорье": добавлены локации и мобы,
  изменено действие некоторых триггеров.
