### ISSUE TITLE
Задания Астрала (Тренки)

### ISSUE THREAD

**Issue by Rorifer** [windir77/Sowmud#32]
В справке указано, что выпадение не 100% для случайной награды.
В описании задания на тренировки нет указания шанса выпадениея.
Судя по опросу  (большинство думает , что 100%.) и статистике - в большинстве случаев падает с первого раза - смею предположить что шанс 100%.
Однако в части случаев ингр не дропается.
Так же ингр не дропается, если при первом репопе его каким-то образом потерять (украли, не поднял)
После этого ингр может не упасть до ребута сервера.

**Comment by windir77** [comment]
Однако в части случаев ингр не дропается. - ингр не дропается одновременно для двух квестов, если ингр и моб совпадают (такое бывает), т.е упадет только 1 ингр из 2х, второй только на второй заход и в инве старого быть не должно.

**Comment by Rorifer** [comment]
Я говорю именно про случай, когда в инвентаре или в мире нет ни одного ингра из выданных астралом, но он не дропается.

http://prntscr.com/h5bhtl

http://prntscr.com/h5bi3f
