### ISSUE TITLE
баг/небаг

### ISSUE THREAD

**Issue by Rorifer** [windir77/Sowmud#45]
Шел на спидволке - слетела прокла по времени - словил слеп

Западная лесистая улица
[ Exits: N E ]
8385H 1685M 1544V 25060319MX 2243026C Вых:СВ> 

Перекрестная аллея
[ Exits: E S W ]
Звездные фонари освещают дороги города... светятся.
Изогнутый деревянный указатель висит на столбе... светится.
вст
колд сл.света
Вы ослепли!
Чувство неуютности пропало.
8385H 1685M 1543V 25060319MX 2243026C Вых:> 
колд сло.све
Здесь темно...
[ Exits: None! ]
8385H 1685M 1543V 25060319MX 2243026C Вых:> 
колд сло.све
Здесь темно...
[ Exits: None! ]

**Comment by fungoter** [comment]
Слепь заклом то получилось снять?
